In [1]:
import pandas as pd

df = pd.read_csv("conversion_data_train.csv")

In [4]:
df.drop("converted", axis=1).drop_duplicates()

        country  age  new_user  source  total_pages_visited
0         China   22         1  Direct                    2
1            UK   21         1     Ads                    3
2       Germany   20         0     Seo                   14
3            US   23         1     Seo                    3
4            US   28         1  Direct                    3
...         ...  ...       ...     ...                  ...
284434       US   22         0  Direct                   23
284483    China   61         0     Seo                    7
284493       US   60         1     Ads                    1
284548       US   64         0     Seo                    4
284563  Germany   40         1     Seo                   13

[13942 rows x 5 columns]

In [8]:
df["combinaison"] = df.apply(lambda x: x.country + str(x.age) + str(x.new_user) + x.source + str(x.total_pages_visited), axis=1)

In [ ]:
df[df["combinaison"] == obs]["converted"].value_counts().shape[0] > 1

(1,)

In [33]:
df[df["combinaison"] == obs]["converted"].value_counts()

converted
0    2
Name: count, dtype: int64

In [ ]:
interesting_individuals = []

for obs in df["combinaison"].value_counts().index:
    if df[df["combinaison"] == obs]["converted"].value_counts().shape[0] > 1:
        interesting_individuals.append(obs)

In [ ]:
df[df["combinaison"].isin(interesting_individuals)]["converted"]

5         0
17        0
19        0
22        0
24        0
         ..
284554    0
284557    0
284564    0
284566    0
284572    0
Name: converted, Length: 38947, dtype: int64

In [53]:
df[df["combinaison"].isin(interesting_individuals)]["converted"].value_counts()

converted
0    34300
1     4647
Name: count, dtype: int64

In [ ]:
df[df["converted"] == 1].

,country,age,new_user,source,total_pages_visited,converted,combinaison
2,Germany,20,0,Seo,14,1,Germany200Seo14
12,Germany,27,1,Ads,14,1,Germany271Ads14
42,UK,27,0,Seo,16,1,UK270Seo16
127,US,32,1,Seo,19,1,US321Seo19
200,US,41,0,Seo,20,1,US410Seo20
...,...,...,...,...,...,...,...
284434,US,22,0,Direct,23,1,US220Direct23
284464,US,23,0,Seo,15,1,US230Seo15
284486,US,32,0,Seo,21,1,US320Seo21
284563,Germany,40,1,Seo,13,1,Germany401Seo13
284574,UK,23,0,Ads,14,1,UK230Ads14

In [49]:
sum_of_errors

np.int64(9294)

In [12]:
df["combinaison"].value_counts().index[0]

'US311Seo3'

In [5]:
df.drop("converted", axis=1).shape

(284580, 5)

In [ ]:
sum_of_errors = 0
stocks = df[df["combinaison"].isin(interesting_individuals)]["converted"]
for obs in interesting_individuals : 
    sum_of_errors += df[df["combinaison"] == obs].value_counts().iloc[1]

sum_of_errors

np.int64(3343)